Fusing layers... 
Model summary: 157 layers, 7018216 parameters, 0 gradients, 15.8 GFLOPs
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/lx/anaconda3/envs/DCN_py38/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "main.py", line 66, in start_camera
    self.capture_loop()
  File "main.py", line 77, in capture_loop
    ret, frame = self.cap.read() # 读取图像
KeyboardInterrupt
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
['back, 数量：1个.']
Traceback (most recent call last):
  File "main.py", line 199, in <module>
    root.mainloop()
  File "/home/lx/anaconda3/envs/DCN_py38/lib/python3.8/tkinter/__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
